[package]
name = "nano_batch_rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "nano_batch"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.27.1"
# "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8
features = ["abi3-py38"]